###
GET http://localhost:8080/client/f147e891-e3c6-47a8-a68a-46daf35542f6
Content-Type: application/json

###
POST http://localhost:8080/client
Accept: application/json
Content-Type: application/json

{
  "firstName": "Клиент",
  "lastName": "Клиент"
}

###
POST http://localhost:8080/client
Accept: application/json
Content-Type: application/json

{
  "firstName": "Клиент",
  "lastName": "Клиент",
  "email": [
    {
    "email": "321",
    "isPrimary": false,
    "parentId": "d326a9c0-ba38-4809-aa9f-483a026f4d47"
    },
    {
      "email": "wqe@qwe.wqe",
      "isPrimary": true,
      "parentId": "d326a9c0-ba38-4809-aa9f-483a026f4d47"
    }],
  "phone": [{
    "phone": "89998887766 asqwqwqwqwdsadas",
    "parentId": "d326a9c0-ba38-4809-aa9f-483a026f4d47"
  }]
}

###
PUT http://localhost:8080/client/update
Accept: application/json
Content-Type: application/json

{
  "id": "c93009d4-b932-43ae-b95c-abd6498daf84",
  "firstName": "Клиентт",
  "lastName": "Клиент Фааа312",
  "version": 7
}

###
PUT http://localhost:8080/client/update/light
Accept: application/json
Content-Type: application/json

{
  "id": "c93009d4-b932-43ae-b95c-abd6498daf84",
  "firstName": "Клиенгт",
  "lastName": "Клиенгт",
  "middleName": " ",
  "version": 2
}

###
DELETE http://localhost:8080/client/4
Content-Type: application/json

###
GET http://localhost:8080/client/list?pageSize=22
Content-Type: application/json